[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "a926b5f14026f000616e7e98a07a8b0dd6b3ea16"
os = "macos"

    [[CUDA_full.download]]
    sha256 = "3514bc48e010e1c97bb5244d68982e08e772ca96986cfcdebef9ebdffc371e5b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+0/CUDA_full.v10.2.89.x86_64-apple-darwin14.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "0cb862f4e965765e8fd65ee01f4f23bf6809e40c"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "f93668b791171982b96ff4baf9b8baa820ed275b51d8f7ae65d303c82ea014d3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+0/CUDA_full.v10.2.89.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "ed8416749eb28c117268cb8d14ba80c363c9384b"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "0412fa9ade3a63fc078f059708f5a18c3069c24560a512eb73738edb5152e49c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+0/CUDA_full.v10.2.89.x86_64-w64-mingw32.tar.gz"
