[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "9f63ed889c5f38a6687c70ce340cc03c64efd05a"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "60e6f614db3b66d955b7e6aa02406765e874ff475c69e2b4a04eb95ba65e4f3b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+5/CUDA_full.v10.2.89.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "efc0974ee23ee8fb7fa948521a923b75e1854cf9"
os = "macos"

    [[CUDA_full.download]]
    sha256 = "3991a667e52e3a56a2037d74911dca4a9a621ac633856eb3f58a5b0ec5790b1a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+5/CUDA_full.v10.2.89.x86_64-apple-darwin.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "4da68a3f0745e4efd1697c977a46cbfb35f3439e"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "0edac5d2a3966b82b0c4165579027639ed4d493a2cafb91b8965402df542cfab"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+5/CUDA_full.v10.2.89.x86_64-w64-mingw32.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "98b8c6703c012abdd8117cb6a18f9db2f45de6d3"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "ea0a04b2ce15db35bef2e93d37bde5e592ba7d89bf6fc6c0de93cb636a09bdc3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+5/CUDA_full.v10.2.89.aarch64-linux-gnu.tar.gz"
