[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "3d2b835fdb9327d2336e3fea5aad015ab16d9659"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "a31cdada5f60ffa379d238cb3c7db89011ca5068d79a54408216c6118ea87c5e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.3.1+3/CUDA_full.v11.3.1.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "9f526276d2e5ddc55c9fc6732e4a03ca49256013"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "7d9a8359b7a2d807d7017080035edd47de6cd78e9e0d414d39d78f1290391990"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.3.1+3/CUDA_full.v11.3.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "9b9daf2a069af85989c30d871cc947c0fb38e186"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "1207eb8e1e557c5673f5650d1313493d2d7b16e18f51036bb43d5db68166119e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.3.1+3/CUDA_full.v11.3.1.x86_64-w64-mingw32.tar.gz"
