[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "1cb0cddebc52fb14e686d91a794ec854f21985ca"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "e86cb52db71eb3caecb75277f89fb67593e891dd65bcdc56784879ba855b00b0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.3+3/CUDA_full.v11.0.3.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "360fb44a20a86db46f1f60a78b9be7be4a5c1a9a"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "889a0a007f7cdd53444bf5c13d278448d6a5565f311d694401136048206b1405"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.3+3/CUDA_full.v11.0.3.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "4312ef70a8376a840f15c6426bc236eec1bf068e"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "4f224e5196cc1d325a50dc8680db2df29061826ae9cba8a96f259f0c4ea28ac1"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.3+3/CUDA_full.v11.0.3.x86_64-w64-mingw32.tar.gz"
