[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "9b8fdc73cee547029c746f8abf69b9e1855f0ae5"
os = "macos"

    [[CUDA_full.download]]
    sha256 = "f0cfb38861babd277a11b5782ca28c4764138b376ef97d7e8462a810ed3326ef"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.1.243+2/CUDA_full.v10.1.243.x86_64-apple-darwin14.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "ddfa253b3e6bfbfe34cab2a11221f122302844f7"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "dffcd6ce117621266160d715b8aa2b4ed0fab9e1b36b03d4b01d98bc540ff1a3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.1.243+2/CUDA_full.v10.1.243.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "1e6dbbf65a0a98bf4c0d7b9678e2754ae50cb0ad"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "e7a68def8b62a72fa0b5470cb7d7bc6e6bf3b458dba810a9c19baf4b91cb914d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.1.243+2/CUDA_full.v10.1.243.x86_64-w64-mingw32.tar.gz"
