[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "47002c6344396981cd89880160dcf94b90a5c647"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "377fac2b3a2e5b2f1c0bf86459f039a020d966670f7ff516e59941e24c906ced"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.1.0+0/CUDA_full.v11.1.0.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "9e6f7def14010010b506bec5eb6b41759e4a2f56"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "e653c46c6f9ed08434754610e539a6ccab038f92524923f2db0b0d4480b9f8d1"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.1.0+0/CUDA_full.v11.1.0.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "1be2f4c141464b95ea35466e591f6218e21f2148"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "dc00c83547b2b593fe5428577ac8215f9e83f8749490cee59e46c461a79c79fb"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.1.0+0/CUDA_full.v11.1.0.x86_64-w64-mingw32.tar.gz"
