[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "d31a89559a774da5a0cb96b023b6bc34506b4df7"
os = "macos"

    [[CUDA_full.download]]
    sha256 = "661b8c90351cef937b0d9242d5e1ef2395b874791599aae20fe7683b1f66c555"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v9.2.148+2/CUDA_full.v9.2.148.x86_64-apple-darwin14.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "8c58366e2349e4ac5fae15fed407ddd8ccf7e7b5"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "336b74828d21eb6007732519fcffdf72967f10ee211ea7d748a8dc7a63d996b6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v9.2.148+2/CUDA_full.v9.2.148.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "8b7c83ba6bee6bc9bf6baa5de2b7bfe0fc95918d"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "6f03eaef1781e02bfb948c39e4d5369f8b609d327f0202cee495cfc88722cc57"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v9.2.148+2/CUDA_full.v9.2.148.x86_64-w64-mingw32.tar.gz"
