[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "6ee064164323fa4354acda8658e4677f77f2f4a5"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "454c65d3da6b62b641d271002212bb196ad62ec12c0ed978364ddd29ab181fc4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.2+1/CUDA_full.v11.2.2.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "5f5053d8bb11a7e01e2e88b6130220786d7e36e2"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "86e7ef43a60bfd9120957bf6dfb22fddf1b1676bacd3bdda4d9fa6d82a2fbf4e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.2+1/CUDA_full.v11.2.2.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "f79266d835ac1d6b131815287ac3dd45df2b931e"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "37f7c6b2ecce619b19e04c993578d1fb765782219a608722b65fafb509af1775"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.2+1/CUDA_full.v11.2.2.x86_64-w64-mingw32.tar.gz"
