[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "8ce7fcd1f1646971893260796bf6285d6d3c2590"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "4e36506e412221c42ac88477523d43b02496caf6ef5303acd6824358b17a7710"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.6.2+0/CUDA_full.v11.6.2.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "ca8309914b75a2f22cb91053d81ae6eeca87ee6f"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "63c89c796b0b3622ca998a11ab1124bddeb0143d9bf8bf67ad578f527b577d31"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.6.2+0/CUDA_full.v11.6.2.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "adc5069fb79063f604719079c401a49f80afe310"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "ae94e9db3b05b874cb5f3da5f3628718f3dc70b9f04db551dea099014b808ae1"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.6.2+0/CUDA_full.v11.6.2.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "2d71d77505edf937d60a387b5e5b4b3e9acb90bd"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "f03c073a44ffb8240f161bd1faa99cdf9d50f99698abde59d15b269105c7c8c6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.6.2+0/CUDA_full.v11.6.2.x86_64-w64-mingw32.tar.gz"
