[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "6f62f4068794738432c7a97f13564a71e31f94a6"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "9ce5d98b82c5824533362826a9514e07999b4278346b63ed8428e08c6f7fa305"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.2.1+0/CUDA_full.v12.2.1.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "3ffc4075144ad1e02034787f12ea708af78b140c"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "02bdd92e2e1e2e4e36d0d1e08f6152f746d5c3368169de84a3ff96c56848d429"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.2.1+0/CUDA_full.v12.2.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "568b0813e5457884b85edf6218932426dced9308"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "2813d60edee77dab2b2a506b561a27a9468e0fc3aacefb34d9843e7820b3331b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.2.1+0/CUDA_full.v12.2.1.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "3571a5d30236a81c7ea9a9f33fd4ac73e1c2d7f8"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "9bdb49e596f81567d46ed40fed13157e1a3e5ca8c6a6fda3c5de100718e64eac"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.2.1+0/CUDA_full.v12.2.1.x86_64-w64-mingw32.tar.gz"
