[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "0fac8336eaa7295ff5457f692b184417b9a481cb"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "61a538b1b50472d4a3b2ec2f556e97d1f25e9770a6dbdddf2ac8df39142f15e0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.1+0/CUDA_full.v11.2.1.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "9c7474d788d13de5a80391f561637f2b29045960"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "0a91c29d1b4588eaefc7e7e50d3506263794d6677848fd7bfd769fdf0a7ec3c2"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.1+0/CUDA_full.v11.2.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "1d3569d96f965a3f2d65bfaea84893e7ba351755"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "230e3017d132a5d53f8b31cea84165c6173a796fc3609ab35c1df7a532ec712b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.1+0/CUDA_full.v11.2.1.x86_64-w64-mingw32.tar.gz"
