[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "486d4648cb303fa8486134ad61093d8cca750391"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "34b2bebfbdd922bdd5e861ead70a0c7aa042e9b46d7cbe906d6443d64451211a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.1.1+0/CUDA_full.v12.1.1.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "f9f5ea82cbfaf23112797cd2aa702e558f5cca42"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "a013de9a79c3687c85cfedb552c99030b1cac760e0d08d268e70995c784135a9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.1.1+0/CUDA_full.v12.1.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "663f4cf6e645c06079a52680fb710ee0218a2f56"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "bdf68052821cb2744d268dab31136daf271ca0995985424696b9612229244f7c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.1.1+0/CUDA_full.v12.1.1.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "2cd475e8be379ebf18fed45a14787725db4ae22e"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "c7d42a442e415d6f3ac7101307aa23d71dbca73654471a89818316b95ccb64bb"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.1.1+0/CUDA_full.v12.1.1.x86_64-w64-mingw32.tar.gz"
