[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "d676489ef7960fab914af57af2dbff324184c8ce"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "d93d4da56681fc241df15d98e9a1c7ce7111ee056091a2c1ae86c5c68d3b1816"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.3.0+0/CUDA_full.v11.3.0.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "f9477bcf01ce48088f8cb73990b5571077f7c7f5"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "a99e89a9449d09990adc0264e188a9c432eb476d09c3b5ab90d55126b3b71749"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.3.0+0/CUDA_full.v11.3.0.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "60b6d416e2f7483ac7f5e284c910d18d1977a4ea"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "e142bd52d1fe285e5194483d0c79c2f1694e2bc28845085372c3ea0116f2a67e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.3.0+0/CUDA_full.v11.3.0.x86_64-w64-mingw32.tar.gz"
