[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "250ecf51ce48d46ca556fd49acd49caf2c7b66cf"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "a1cb82cc3adaed10432ea333563394555d25dbd774889fbf86126e8e3bd77d00"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+4/CUDA_full.v10.2.89.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "8ac0c4ef2250ad6b957e5fec36e0e638d1bcaffc"
os = "macos"

    [[CUDA_full.download]]
    sha256 = "f211f50fcf37ad3a6a84660c8b7af58fe0665e9a6a06b663efc02c84723433eb"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+4/CUDA_full.v10.2.89.x86_64-apple-darwin.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "54dfe8868930dc7a81524d66fcf8f659f62a98be"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "bd872cb43f5bd2c01fdd7447bf5e3d8f3118a42ae76d4503b8e6af51a6e4bd9b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+4/CUDA_full.v10.2.89.x86_64-w64-mingw32.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "63e4229bdb509840b3e813bc84449e08e0cf72a7"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "b302f62ebf70b9f9f952eb1f1692f1340072d0d7f93377e7eed569680d4d161a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+4/CUDA_full.v10.2.89.aarch64-linux-gnu.tar.gz"
