[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "f856d2b9ef5088ab694c4fc53e4f6eebfa68f614"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "e31479b573c214483d2a0f312f88928713e3b9676d1d73c48241f2a8503a735d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.3+2/CUDA_full.v11.0.3.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "7352c76216e5a5bea265841522596b1fe21619a3"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "f8a99e0dee0168ec6dc6b0ebe982922cfcbaeee7cfad618edf91ecfc1335e0e2"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.3+2/CUDA_full.v11.0.3.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "ecda06e5670ea378f5534f7b1502c6986a9d35ea"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "626cc65b9a782f2ff7ea48cc79ddac0b8fea63cbc5eeab81d005baa1fb2d8ab2"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.3+2/CUDA_full.v11.0.3.x86_64-w64-mingw32.tar.gz"
