[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "bbf91e4c930d2587ca6c1dcbf56067691c6952c2"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "632221cc9825837374ab1700cc0a00a542f423ee7973b357661fb85be89edaec"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.1.1+1/CUDA_full.v11.1.1.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "4f3efabbcdb81d4fa5688f6c43275db191df3679"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "308d5b3afc95536a5fa2db4eacb7358ce0c6f121833765d95172c7feffffae43"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.1.1+1/CUDA_full.v11.1.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "077be2bb7475b50714f6dc7a70dd266698232c67"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "a39bd7fdcae1fee1d5d56d11ed3c3463e82e71f40578990f533c3747ad73294b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.1.1+1/CUDA_full.v11.1.1.x86_64-w64-mingw32.tar.gz"
