[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "c58b7ee55b5bf522103ac5568c4da1600d1d49c1"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "9ae00d36d39b04e8e99ace63641254c93a931dcf4ac24c8eddcdfd4625ab57d6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.3.1+1/CUDA_full.v11.3.1.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "03e041338e93c08206fa74531411231ef1d0b563"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "34f0a379be67597d1f5905ce209f57b4a8c2f672f0c470d97e61e100042d77d9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.3.1+1/CUDA_full.v11.3.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "73af4bf2015fbd801fecfb83b5761c895843f728"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "acba722d9456d36fb5952a807cc6cc612ca28c82d4f610c6c56511fa0ef7b4c9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.3.1+1/CUDA_full.v11.3.1.x86_64-w64-mingw32.tar.gz"
