[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "e34f375b31613ffed53fa8506cf9512063a72b9a"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "181580bf75258d37607c9384079ce6d38b685ecd810448ffab8c4477b2c140ec"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.5.0+0/CUDA_full.v11.5.0.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "7d433404a792eec65efd62dd21a3c9bc554836a9"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "019d42c20cd0d20b2052fdbc16646f17d65473b80bbbf3f3c233dd60620c5377"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.5.0+0/CUDA_full.v11.5.0.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "4c6b76fdd28d6f63f1f03524efec268aa2467c9f"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "781e1b7d3c3f2bb99ba0ca41c85a4d424f7508aa913fea3f73bdc47655cd0dd8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.5.0+0/CUDA_full.v11.5.0.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "ea835f9778690cd1e32a3c2bb9373be5e9cfbb83"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "0c3adc9d90b69beb0730718247fcb34660fed03d262a7cf31f273241df21792f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.5.0+0/CUDA_full.v11.5.0.x86_64-w64-mingw32.tar.gz"
