[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "f72005da2e8f4470b49e212fd6c3c625642c40d1"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "7faa2aa93436214063ae59acab0e656723966d7ceb908483f25ed3929a9133a3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.3+1/CUDA_full.v11.0.3.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "f43c68ba667304445bac0ff5508b59f7d48a10df"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "dadb55dad7f223bb4908a7a90e470da3a12cd64bc3a041c89d07a4b23cf9820e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.3+1/CUDA_full.v11.0.3.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "8324c25b731dcd1361e5cf1e408837cb844457a7"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "0661bc4ea4946223e8e441d8a8163377fedae0fcfb8ba0682c9f4b48577012bf"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.3+1/CUDA_full.v11.0.3.x86_64-w64-mingw32.tar.gz"
