[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "0c66b41a99309a17ff1e166ad8655c71223be099"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "da8361c662cc0e63c9d9b282b830069258e5a7f5350ac6488e5951e971f2b26f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.2+0/CUDA_full.v11.0.2.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "083fdb6f5691355e4f96ec79601c9dfb9790d3ad"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "78634bfc833e1b2c811006f42f71afe30d89b1cf62114dc768fdf50deb287f44"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.2+0/CUDA_full.v11.0.2.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "1811cc8b225c82423c5d0084c93a5ab0ef6ddc11"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "88e9cc3ab6fedb67fea11cdf34604a6789a8e49033bb88016f49f8152ec96228"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.2+0/CUDA_full.v11.0.2.x86_64-w64-mingw32.tar.gz"
