[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "3a671eddc881de36680b608c77d1b435be6a224b"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "b7838dde1f0c2f00f3ecedb2c88f0d382a158eafe2e29862d3d1d34fa1139edf"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.2+3/CUDA_full.v11.2.2.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "a8602f5250c4b376cd855f8123f68d22fef30b29"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "36391f458dc0e921b9883d7aa3f19a940c5fa21163741e0f71d20a7dccd71384"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.2+3/CUDA_full.v11.2.2.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "1c446062134fdfcf65e506469e16ff45c377e32c"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "b7fe93862192d3e1d693a36be77e128b0e1b8ce4c8684980d612aaaf04620fb3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.2+3/CUDA_full.v11.2.2.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "1a8d33fecc1a49bae859f48588bf0a9c07d70821"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "f68f177efb365ad2ac9d8c05b1ee8bd6702a6cc15c0798fa25b87f31383fd88e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.2+3/CUDA_full.v11.2.2.x86_64-w64-mingw32.tar.gz"
