[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "ff447f19073185e1281da9e7f6363a90b56dbc83"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "c8552f07c3ebf808ead024d6399443a86fe12e0433fecf257ceb205f39f0ca86"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.4.2+1/CUDA_full.v11.4.2.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "53ac22b29cb99a9890aaa794f2234263a6a65a12"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "f9dc19a3a86efb494623ab2c041a6a0c2beb671918977d0e58f56d379f7e5ee0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.4.2+1/CUDA_full.v11.4.2.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "59bc30cf565c5800dcabb0be5f3da58b6023d6db"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "f69085851fc569b1b348771af39c4d11f9d1ab1f24b8370861f2f4a46979936f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.4.2+1/CUDA_full.v11.4.2.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "26312e61e772625ea3f7390aaa07a33fa2adde4c"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "fc767f3120935931bd8e4a40bfeecfa3bd0e4d47dca74c17c9ecfb9353da8c87"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.4.2+1/CUDA_full.v11.4.2.x86_64-w64-mingw32.tar.gz"
