[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "dd05c0259b64337ee5bc39bef28598d96624899f"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "6ee3ce181cdfa2be3253c94c4d2ba480f4014699ee0318745f0f4b7bd1e019a8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.8.0+0/CUDA_full.v11.8.0.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "f4baf7e5975abdb69a72ab796c9037e11f2ba0b4"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "2e1a38d0d39ec0240297e29071a73414077b22492d03437840f13e782d7fcadc"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.8.0+0/CUDA_full.v11.8.0.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "82a0ec93e7b954501b5c974b34f7a13fe6ab1d88"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "7af5a960bd259e51b4eafa33e55d273dbc835340de9d72ab0ccbf1082426b9d6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.8.0+0/CUDA_full.v11.8.0.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "915eb65a5c356f6aa975582d66ef9129b2af1ede"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "729fa713e8751e7a6781e2fc21d3ab5c455948327bf42038853dd520a5ab12d7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.8.0+0/CUDA_full.v11.8.0.x86_64-w64-mingw32.tar.gz"
