[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "cb7b5d955a2b77ea98ccfc51044d4408dd52a9dd"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "1234b8119520c4934ed751552a330b594f68ea1da23c4ce770ddd1df8df928f2"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.5.2+2/CUDA_full.v11.5.2.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "9cc2012e45b82f2d1b9163f34b38d54b315b7aed"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "9bcf0c4912d9f07d9a7486a9d9714d16be2606ade4a848017f9bcf8439e5f15d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.5.2+2/CUDA_full.v11.5.2.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "f79aea7c790fd52a993ce7fe7b70f77a7ff83460"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "e3d5b6200bbee6e31e3543c9fd1e8e6b9ea8dce2f899656281bba2b53ca29914"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.5.2+2/CUDA_full.v11.5.2.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "23b55707217e5404725442d680fb3dc13bc13a2c"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "dd65eda869dd564dcbc2d47fa4ffe8bd94631fd3d8d961945a4ab0de1743a9fa"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.5.2+2/CUDA_full.v11.5.2.x86_64-w64-mingw32.tar.gz"
