[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "460cd92dad9b9253772902b0162fbd6b074c8182"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "70c88f274060d4477db1b247d4ff07abd879335d911487674905a521479ed4d3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.0.1+1/CUDA_full.v12.0.1.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "2a8a23e6a0e1b01b5032f88647b3d4e8743a1932"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "fd01da5bedc32bb4b41325660f23b4d3501977d82d5ac4f36ea2b756f22dd375"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.0.1+1/CUDA_full.v12.0.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "e77126f14cec0b6fc33abc59d5e3c71f03d187a9"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "a91748bb7c35f37041a045d8d7ecba2a030956bd2006d914beeb96ce34d5f2cb"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.0.1+1/CUDA_full.v12.0.1.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "d6183a6335bca454e1bbc472cde3d2574b64c7ef"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "1c698417bdc734f5ca9e8c9f0cb093289d6b03b14bb5646168c8d36e28201658"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.0.1+1/CUDA_full.v12.0.1.x86_64-w64-mingw32.tar.gz"
