[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "ec0152f5ad7b1767c07abaddd1d8989858bc92fa"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "99146b1c6c2fe18977df8618770545692435e7b6fd12ac19f50f9980774d4fc5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.0.1+2/CUDA_full.v12.0.1.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "dd0d30c26594f623a5d390b8df68e04a7423ace5"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "2f1220601be83d3be0e2d404d67703769b2e71afc992453ae48df2c5d3286a3e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.0.1+2/CUDA_full.v12.0.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "411a5f663527843bcd56f5c4b797251faaa75d4e"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "53f92aba52d7adbe9c3094d145cf7722932175155936d9d3fe9f04a26730de82"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.0.1+2/CUDA_full.v12.0.1.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "0ae02ae50c9820e65efaeb56eafcef81352d64f6"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "73d53027ca1e99eaa1089b24e904fcd555a54b03a2651e7f5b7bfba39e183ce4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.0.1+2/CUDA_full.v12.0.1.x86_64-w64-mingw32.tar.gz"
