[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "b94cab4ab7ac7b68250a887de1d3e593168b4482"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "f699fe4b6b80b09659d8fe34164e4746c01e71269e2c89671f0c25c635f917ff"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.7.1+0/CUDA_full.v11.7.1.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "7bc28b7c4bc28ac8e961ab924e892bc21987cd49"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "ea1256a5aeeb7f847ca9f67299923ffe5351b03550945da87941cdae7d28ec02"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.7.1+0/CUDA_full.v11.7.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "20c6ccc86143d384f78b1596ac9f080b1de93ae8"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "7da2be46cd6752e2bb5f26a92317d6732c006734de3cb37a0cca921030d64794"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.7.1+0/CUDA_full.v11.7.1.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "87881115a0df73f383c245e360b94ed2047c8935"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "eea5f5c9b76935c81e043c0f31ec31f44083522e68b8ee737d618ac42ed59d5b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.7.1+0/CUDA_full.v11.7.1.x86_64-w64-mingw32.tar.gz"
