[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "d1d46b8815c4826da8709c59664639900fdea1eb"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "2092df06e07c260981ca374a4a3185a098692d4a2d86b7242524dff8a240bfc8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.0+0/CUDA_full.v11.2.0.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "ea219751f09b587a36dc004d1ff1672f16ead9e5"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "2d95aac347c9f52d76720cca323f291ce746452fc781a59af865390e2360e67b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.0+0/CUDA_full.v11.2.0.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "7aa72a554c03e449f7a26b38ff143da6564ffa32"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "44a21e67951b9fcdd22b0eb994578d6ac8836e3316b053d56e73131d965d6e61"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.0+0/CUDA_full.v11.2.0.x86_64-w64-mingw32.tar.gz"
