[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "3ba15d2b121b7b9d208a945c36ebf74f620ba17a"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "43ce5210ae7e7e2c14a3d8c6f8959feb2aeb7c5cea01344637129a1ffe9b6af2"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.3.1+2/CUDA_full.v11.3.1.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "475d539dfe9eeb159d8ff6000603835f66d52a1c"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "681765c3a3b48cec6e60ceb8cdf8822ba6f6ffda5a1e6d5db2c7f206ed2da1af"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.3.1+2/CUDA_full.v11.3.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "7c623b324db14cc48de7a82136c28021e213043a"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "6ac08ad551af6a8a4c537bbf0a491b5f043f771801c8625db61cf8a335955531"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.3.1+2/CUDA_full.v11.3.1.x86_64-w64-mingw32.tar.gz"
