[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "60eca20de2327106566ee29c21db12831c4b86b1"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "cc4f5bf68c9608a1ec7b45ed0b578840c803aee181b4b97c4827dee1b55a6afa"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.5.1+0/CUDA_full.v11.5.1.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "dc325b05d67c84d9cb49783bbbd58b44eeeef654"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "ac906ca59a1a8c0949c73959d14f320d405477adb57214ffbff99cd8f9a3ecbe"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.5.1+0/CUDA_full.v11.5.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "2d2387ed6fb2cdc00366cbd5e6dfc307df45bccc"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "37bc00c6a11b6afe0fd2117d660a3d82444366bd3204d901f85a2a5a1cb1d51e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.5.1+0/CUDA_full.v11.5.1.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "2eb40acbaa8f3ee25a85fc23ac51a1b832556a91"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "30ae7bb33cea3de46f37f80e4eb0215b318f5060609dba44ba5499b204a27703"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.5.1+0/CUDA_full.v11.5.1.x86_64-w64-mingw32.tar.gz"
