[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "4115d8a29e5f3ec39439e5c963fadf3b35dfc309"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "3e8bf85a858c196d46b417addf89f30d31f037e47edd63b6cbfeb3d725a7258a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.0.1+0/CUDA_full.v12.0.1.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "7c7cb153f06727a0143a0667a446004a5152f2ad"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "38d3c96725baee74c9963710850ae7b34f4151c44ea3b710f13c4183cfa26f94"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.0.1+0/CUDA_full.v12.0.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "fd8d1d2fe2b08dc2fded84f6fefc13131aaa92e5"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "c291cbb826957636f910e79d83ceef15ecd801e821dfe1d5a7c833cc429dcf71"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.0.1+0/CUDA_full.v12.0.1.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "d4e7782e6152b3eb8dee7743cfe3404a17a2a845"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "de4e9d55a098bacbbc605cce44e84eeb8de721696405dc384e495f4c4b52f419"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v12.0.1+0/CUDA_full.v12.0.1.x86_64-w64-mingw32.tar.gz"
