[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "c21ac5a4952aa9b577b62c94846c0dcfea677180"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "7605f37db8ae7502b9b64df2ae943e5f8b303bf42abfbd69490f315a2b70eeb1"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.7.0+0/CUDA_full.v11.7.0.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "6a79a9ce8cc666d2aac1c2bbea09aed0606b7c6a"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "f10fe2a600e54bb714eb2a623b39637b2fd98ffb751d7807883847eeba2395d0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.7.0+0/CUDA_full.v11.7.0.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "6e70572cb62b2d65396f9cdc0fb085b1f1a94b5b"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "39027284666a6caac0e806ee0a13a7f5ad788b95338d98c66922187492484815"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.7.0+0/CUDA_full.v11.7.0.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "6838c7b1d6bf66ddb8e20bb20305b1dee9b60c90"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "3f255e7f5dd75d5269c897e3eb381b2d91e09ee7ac833c47c5cddc4596d85938"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.7.0+0/CUDA_full.v11.7.0.x86_64-w64-mingw32.tar.gz"
