[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "fe6063c75118dba5d92448c655c762c3989928d2"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "1f0e78e2336e2669b4cd6ae796315f5331211cc2e3e6f6111253015f3ea6528f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.8.0+3/CUDA_full.v11.8.0.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "51416d06135113bd41b7c76c894eaca47dcce756"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "529e89345a5e16520e55a001c8908db78fe8fe37a10b9975e21d82fb71a45e6d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.8.0+3/CUDA_full.v11.8.0.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "aarch64"
git-tree-sha1 = "f4ee6db8108720b17865637ffc4010a4c3694f6e"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "389e23a4853372e2e7571cca9d2abe6011d50a157c72a86270875cae3625ab91"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.8.0+3/CUDA_full.v11.8.0.aarch64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "1852d02a2444b1ca9d1b806f3de5f365fdef33df"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "c368376e5a41c69d6d47986760814525b77f2dc02d336d80ecdbd47672a19ee9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.8.0+3/CUDA_full.v11.8.0.x86_64-w64-mingw32.tar.gz"
