[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "636cbc898414f089023ac78b44894297495b735d"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "dabcb18370f4839498a2a10c8e05cbebf6d6fe944b1daf6fa9123b38c5140525"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.3+0/CUDA_full.v11.0.3.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "f833afd22080807355aa47d4b0fe07523235bd48"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "2f511991f790e87ae507e613dd06d1181601e6b1f6cec8e6b00642278cdbec1c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.3+0/CUDA_full.v11.0.3.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "a82244ecc8b1b18339142dafeda58d359626d8e6"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "19706e72cee481cfc18170792c08d22ea630555c365bffe502689fb68340f559"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.0.3+0/CUDA_full.v11.0.3.x86_64-w64-mingw32.tar.gz"
