[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "4f2b116aedac4a714740321abd0aff965d90f04d"
os = "macos"

    [[CUDA_full.download]]
    sha256 = "824431d61745b2affd018f6f8cdad5656421e13921c0b147f11cdea4f9ad836c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.0.130+2/CUDA_full.v10.0.130.x86_64-apple-darwin14.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "7a47de18e8ebaa40500c11c32d29e69da1530975"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "a39b1856d5650eb1a9f6353dda6cb4353b23f9680a898cdd3081527175cb46c7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.0.130+2/CUDA_full.v10.0.130.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "3769880fa032aee151060215a63c9deddaeec944"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "13efb34cdb16f277c64f0290ca4faa2b51f44fdf598869a2759b5dd985aff5a3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.0.130+2/CUDA_full.v10.0.130.x86_64-w64-mingw32.tar.gz"
