[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "61a14d77828bc0a0677c23f2789ae2da6eb2f226"
os = "macos"

    [[CUDA_full.download]]
    sha256 = "b39010d942b98568fad4f860cc2a09e128eb007187789b1e0b83c37ca7e46cb4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+1/CUDA_full.v10.2.89.x86_64-apple-darwin14.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "ed981d97529c65531ea589036f37f8ea3a4de3b9"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "c222e6fda985c84dd1a204823a33a0097c8e21d50ae65ea4a0a6d766cb063848"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+1/CUDA_full.v10.2.89.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "f214b684035b5f82d61be92c95ddfa15f255d9a9"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "585d4025195ce7cef46d61275bbcfd93fac55e8dbcb33246b8bf25b6252904fc"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.2.89+1/CUDA_full.v10.2.89.x86_64-w64-mingw32.tar.gz"
