[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "59172198ec76ea7ee8fa48623c552818ceb1affa"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "33e2a086570ac7576f8394b49776f57950ade703b7829349c0ae50ee6cc2385d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.0+1/CUDA_full.v11.2.0.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "powerpc64le"
git-tree-sha1 = "674798e494a5ca12b494f3a8ff221eddc1090713"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "050e6f5d4ad2b664d16cebdfd6d9992321f3d67a97fa56322ba9b576bc17f7f1"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.0+1/CUDA_full.v11.2.0.powerpc64le-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "56c5e8021ee6b30af232090222680ce8b497da70"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "ed1ae710a3b43e0cc01cd364c9069d8b0a74cecf2eac611351c7f38e34ea065e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v11.2.0+1/CUDA_full.v11.2.0.x86_64-w64-mingw32.tar.gz"
