[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "768cd81b3f29c42de775b286ddab7ba59824f5da"
os = "macos"

    [[CUDA_full.download]]
    sha256 = "33f5ca4ba4862e40522380bb92cf652a84d595ae798dec66c6a3d0dd0dc3cf81"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.1.243+0/CUDA_full.v10.1.243.x86_64-apple-darwin14.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "ce02776dfe49896031bc14077df1e002f26396d4"
libc = "glibc"
os = "linux"

    [[CUDA_full.download]]
    sha256 = "7b4f103ffbe1d6638d1cf59b82f2143967e2475b01fd1336472c2ebcce97b4a8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.1.243+0/CUDA_full.v10.1.243.x86_64-linux-gnu.tar.gz"
[[CUDA_full]]
arch = "x86_64"
git-tree-sha1 = "4350d7bd0dcec32cc94853da8bd0573b8ab15349"
os = "windows"

    [[CUDA_full.download]]
    sha256 = "73f68f5dc354a7457d7acaf25ca341ffbc918edebc20168bb5b52f00706f5456"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_full_jll.jl/releases/download/CUDA_full-v10.1.243+0/CUDA_full.v10.1.243.x86_64-w64-mingw32.tar.gz"
